### ISSUE TITLE
The Broccoli Plugin: [StylusCompiler] failed with: Error: File not found: /app/styles/style.styl

### ISSUE THREAD

**Issue by msalahz** [drewcovi/ember-cli-stylus#15]
Hi, I have the following options in build file :

```
stylusOptions: {
    inputFile: "style.styl"
}
```

and it was working fine and compile app/styles/style.styl into dist/assets/app.css
now i need to use ember-paper which require ember-cli-sass so i simply installed it and suddenly i got this error  

```
The Broccoli Plugin: [StylusCompiler] failed with:
Error: File not found: /app/styles/style.styl
in any of the following include paths:
  /home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/tmp/stylus_compiler-input_base_path-WjnwMXAU.tmp/0
    at Object.findFileSync (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/include-path-searcher/index.js:12:9)
    at StylusCompiler.build (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/broccoli-stylus-single/index.js:34:35)
    at /home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at StylusCompiler.Plugin (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at StylusCompiler.CachingWriter [as constructor] (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/broccoli-caching-writer/index.js:21:10)
    at new StylusCompiler (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/broccoli-stylus-single/index.js:21:17)
    at StylusPlugin.toTree (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli-stylus/index.js:20:10)
    at /home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessCss (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:152:10)
    at EmberApp.styles (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1262:28)
    at EmberApp.toArray (/home/mzaghloul/mvp_opencoast/ember_frontend/web_frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)
```

any help ?

**Comment by scottkidder** [comment]
I'm in the same boat. There are some useful addons (ember-paper, ember-modal-dialog, etc) that require ember-cli-sass. How can we make these work together?

**Comment by brancusi** [comment]
Any updates on this one? Definitely would be great to use multiple preprocessors.

**Comment by drewcovi** [comment]
This is a request for broccoli-stylus-single. All this plugin does is bridge that functionality with ember-cli. I can re-open if presented with evidence to the contrary. But at this point I'm less able to support this plugin and willing to hand the reigns to anyone willing to submit a PR or become a regular contributor.
